language: ruby
sudo: false
cache: bundler
rvm:
  - 2.5.3
  - 2.6.1
  - 2.7.1
  - 3.0.0
gemfile:
  - gemfiles/rails_52.gemfile
  - gemfiles/rails_60.gemfile
  - gemfiles/rails_61.gemfile
  - gemfiles/http4.gemfile
env:
  - TEST_SUITE=rake

before_install:
  - gem update bundler

script:
  - bundle exec $TEST_SUITE

matrix:
  include:
    - rvm: 3.0.0
      gemfile: gemfiles/rails_61.gemfile
      env: TEST_SUITE="rubocop lib/ spec/"

notifications:
  email: false
